apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
        - name: mywebapp
          image: sanjeeva121/mywebapp:latest   # <-- This is where image goes
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
spec:
  type: NodePort
  selector:
    app: mywebapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007

ports:
  - name: http
    containerPort: 5000   # or 80 if your app runs on 80
