apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
  labels:
    app: mywebapp
spec:
  type: NodePort
  selector:
    app: mywebapp
  ports:
    - protocol: TCP
      port: 80        # service port
      targetPort: 5000  # container port (Flask app runs on 5000)
      nodePort: 30007   # optional: expose service on this NodePort
